db_main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage
from db_site.views import register
from db_site.forms import UserLoginForm


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('login/', views.LoginView.as_view(authentication_form=UserLoginForm), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', register, name="register"),
    path('feedback/', include('feedback.urls')),
    path('tracker/', include('tracker.urls')),
    path('telegram/', include('telegram_bot.urls')),
    path('documentation/', TemplateView.as_view(template_name='documentation.html'), name='doc_page_url'),
    path('favicon.ico/', RedirectView.as_view(url=staticfiles_storage.url('/db_site/favicon/LogoADL.gif'))),
    path('', include('db_site.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tracker/urls.py
from django.urls import path
from .views import task_list, task_page, task_form, create_task_for_exist_task, change_task_status, change_comment

urlpatterns = [
    path('<str:lab>/all/', task_list, name='task_list_for_current_lab'),
    path('<str:lab>/all/<int:pk>/', task_page, name='task_page_url'),
    path('<str:lab>/all/<int:task_pk>/change_comment/<int:pk>/', change_comment, name='change_comment_url'),
    path('<str:lab>/create_new_task/', task_form, name='new_task_form_url'),
    path('<str:lab>/all/<int:pk>/update_task/', task_form, name='update_task_url'),
    path('<str:lab>/all/<int:pk>/create_new_task/', create_task_for_exist_task, name='create_task_for_task_url'),
    path('<str:lab>/all/<int:pk>/change_status/', change_task_status, name='change_task_status_url'),
]

tracker/models.py
from django.db import models
from db_site.models import BigObject, Profile, LabName, del_path
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.shortcuts import reverse
from django.utils.html import mark_safe
from django.utils.formats import date_format
from markdown import markdown
from threading import Thread
import os


def generate_path_for_files(instance, filename):
    if instance.comment:
        return 'comments/{0}/{1}'.format(instance.comment.pk, filename)


def get_all_children_for_task(top_task, include_self=False, status=None):
    top_level = 1
    if status is None:
        status = ['IW', 'NW', 'CT', 'CF']

    all_children = []

    def get_children_for_task(task, level):
        children = Task.objects.filter(parent=task)
        for child in children:
            if child.status in status:
                all_children.append([child, level])

            if child.if_get_children():
                if child.status in status:
                    level += 1
                get_children_for_task(child, level)

    if include_self:
        if top_task.status in status:
            all_children.append([top_task, 1])
            top_level += 1

    if top_task.if_get_children():
        get_children_for_task(top_task, top_level)

    return all_children


class Task(models.Model):
    class ChoicesStatus(models.TextChoices):
        OPEN = 'NW', _('Не в работе')
        IN_WORK = 'IW', _('В работе')
        CLOSE_TRUE = 'CT', _('Закрыто (решен)')
        CLOSE_FALSE = 'CF', _('Закрыто (не решен)')

    parent = models.ForeignKey(to='self', verbose_name='Родитель', on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=200, verbose_name='Название')
    lab = models.ForeignKey(to=LabName, verbose_name='Лаборатория', on_delete=models.SET_NULL, null=True)
    create_date = models.DateTimeField(verbose_name='Дата и время создания', editable=False)
    last_modified = models.DateTimeField(verbose_name='Дата и время последнего изменения', editable=False)
    start_date = models.DateTimeField(verbose_name='Дата начала', editable=False, blank=True, null=True)
    end_date = models.DateField(verbose_name='Дата окончания')
    close_date = models.DateTimeField(verbose_name='Дата закрытия задачи', editable=False, blank=True, null=True)
    text = models.TextField(verbose_name='Описание', blank=True, null=True)
    creator = models.ForeignKey(
        verbose_name='Создатель', to=Profile, on_delete=models.SET_NULL, null=True, blank=True,
        related_name='creator_task'
    )
    executors = models.ManyToManyField(
        verbose_name='Исполнители', to=Profile, blank=True,
        related_name='executors_task'
    )
    big_object = models.ForeignKey(
        to=BigObject, verbose_name='Объект', on_delete=models.SET_NULL, null=True, blank=True
    )
    status = models.CharField(
        max_length=2,
        choices=ChoicesStatus.choices,
        default=ChoicesStatus.OPEN,
        verbose_name='Статус'
    )
    new_comment_for_executors = models.ManyToManyField(
        verbose_name='Новые комментарии для исполнителей', to=Profile, blank=True,
        related_name='executors_task_new_message'
    )
    privat = models.BooleanField(verbose_name='Приватная задача', default=False, blank=True)

    class Meta:
        verbose_name = 'Задача'
        verbose_name_plural = 'Задачи'
        ordering = ['-create_date']

    def __str__(self):
        return f'{self.name}'

    def save(self, *args, **kwargs):
        self.last_modified = timezone.now()
        if not self.id:
            self.create_date = timezone.now()
            if self.status == 'IW':
                self.start_date = timezone.now()
        else:
            old_self = Task.objects.get(pk=self.pk)
            if old_self.status == 'NW' and self.status == 'IW':
                self.start_date = timezone.now()
            if old_self.status == 'IW' and self.status in ['CT', 'CF']:
                self.close_date = timezone.now()
        super(Task, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('task_page_url', kwargs={'lab': self.lab.slug, 'pk': self.pk})

    def if_get_children(self):
        if Task.objects.filter(parent=self):
            return True
        return False

    def can_close(self):
        all_children = self.get_all_children()
        all_done_children = self.get_all_children(status=['CT', 'CF'])
        if all_children == all_done_children:
            return True
        return False

    def get_children(self):
        return Task.objects.filter(parent=self)

    def get_all_children(self, include_self=False, status=None):
        return get_all_children_for_task(self, include_self, status)

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.text))

    def get_color(self):
        if self.status in ['NW', 'IW']:
            days_left = self.end_date - timezone.now().date()
            if days_left.days < 0:
                return '#ffa3a3'
            elif 0 <= days_left.days <= 3:
                return '#fff9a3'
            else:
                return '#a9ffa3'
        else:
            return None

    def add_new_comment(self, text, author):
        new_comment = CommentForTask()
        new_comment.text = text
        new_comment.task = self
        new_comment.user = author
        new_comment.save()
        self.new_comment_for_executors.set(self.executors.all())
        self.create_tg_message_text(comment=new_comment, author=author)
        return new_comment

    def create_tg_message_text(self, comment, author):
        message = f'В задаче <b>{self.name}</b> есть новое сообщение: \n'
        name = comment.user.name
        if comment.user.robot:
            name += ' <i>(робот)</i>'
        message += f'<strong>Автор</strong> : {name}\n'
        message += f'<strong>Дата</strong> : {date_format(comment.date)}\n'
        message += comment.get_message_as_markdown()
        Thread(target=self.send_message_in_tg, args=(message, author)).start()

    def send_message_in_tg(self, message, author=None):
        from telegram_bot.views import send_message
        users = self.executors.filter(tg_id__isnull=False, tg_chat_id__isnull=False)
        for user in users:
            if user != author:
                send_message(text=message, user=user)

    def add_robot_comment(self, text, author):
        self.new_comment_for_executors.set(self.executors.all())
        self.new_comment_for_executors.remove(author)
        robot = Profile.objects.filter(robot=True).order_by('?')[0]
        if robot:
            new_comment = CommentForTask(
                task=self,
                user=robot,
                text=text
            )
            new_comment.save()
            self.create_tg_message_text(comment=new_comment, author=author)

    @staticmethod
    def get_task_tree(lab, private=False, user=None):
        all_task = []
        all_done_task = []
        if private is True and user:
            top_task_for_lab = Task.objects.filter(lab__slug=lab, parent=None, privat=True, creator=user)
        else:
            top_task_for_lab = Task.objects.filter(lab__slug=lab, parent=None, privat=False)

        for task in top_task_for_lab:
            all_task.append(task.get_all_children(include_self=True, status=['NW', 'IW']))
            done_task = task.get_all_children(include_self=True, status=['CT', 'CF'])
            if len(done_task) > 0:
                all_done_task.append(done_task)
        return all_task, all_done_task


class CommentForTask(models.Model):
    task = models.ForeignKey(to=Task, on_delete=models.CASCADE, verbose_name='Комментарий к задаче',
                             related_name='comments')
    user = models.ForeignKey(to=Profile, on_delete=models.SET_NULL, null=True, verbose_name='Пользователь')
    date = models.DateTimeField(verbose_name='Дата и время комментария', editable=False)
    text = models.TextField(verbose_name='Текст комментария')

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ['date']

    def __str__(self):
        return f'{self.user.name}, {self.task.name}'

    def save(self, *args, **kwargs):
        if not self.id:
            self.date = timezone.now()
        super(CommentForTask, self).save(*args, **kwargs)

    def get_absolute_url_for_change(self):
        return reverse('change_comment_url', kwargs={'lab': self.task.lab.slug, 'task_pk': self.task.pk, 'pk': self.pk})

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.text))


class FileForComment(models.Model):
    comment = models.ForeignKey(CommentForTask, on_delete=models.CASCADE, related_name='files', verbose_name='Файл')
    file = models.FileField(upload_to=generate_path_for_files, verbose_name='Файл', blank=True)

    class Meta:
        verbose_name = 'Файл к комментарию'
        verbose_name_plural = 'Файлы к комментариям'
        ordering = ['comment']

    def __str__(self):
        return f'Файл для : {self.comment}'

    def filename(self):
        return os.path.basename(self.file.name)

    def delete(self, *args, **kwargs):
        full_path = str(self.file.path).rsplit(os.sep, 1)[0]
        self.file.delete(save=False)
        del_path(full_path)
        super().delete(*args, **kwargs)

tracker/forms.py
from django import forms
from .models import Task, CommentForTask, FileForComment
from db_site.models import Profile, BigObject
from django.utils.translation import ugettext_lazy as _


class TaskForm(forms.ModelForm):
    parent_list = None
    executor_list = None
    big_objects_list = None

    class Meta:
        model = Task
        fields = ['executors', 'big_object', 'name', 'text', 'end_date', 'privat']

        widgets = {
            'executors': forms.SelectMultiple(attrs={'class': 'form-control'}),
            'big_object': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'end_date': forms.TextInput(attrs={'class': 'form-control', 'type': 'date', 'placeholder': 'Дата'}),
            'privat': forms.CheckboxInput(attrs={'class': 'form-check-label'})
        }

    def __init__(self, *args, **kwargs):
        lab = kwargs.pop('lab')
        self.executor_list = Profile.objects.filter(lab__slug=lab)
        self.big_objects_list = BigObject.objects.filter(base__lab__slug=lab, top_level=True)
        super(TaskForm, self).__init__(*args, **kwargs)
        self.fields['executors'].queryset = self.executor_list
        self.fields['big_object'].queryset = self.big_objects_list
        if 'instance' in kwargs.keys():
            task = kwargs['instance']
            if task.get_children():
                self.fields['privat'].widget = forms.HiddenInput()


class TaskForTaskForm(forms.ModelForm):
    executor_list = None

    class Meta:
        model = Task
        fields = ['executors', 'name', 'text', 'end_date']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 4, 'id': 'new_task_for_task__text'}),
            'end_date': forms.TextInput(attrs={'class': 'form-control', 'type': 'date', 'placeholder': 'Дата'}),

        }

    def __init__(self, *args, **kwargs):
        lab = kwargs.pop('lab')
        self.executor_list = Profile.objects.filter(lab__slug=lab)
        super(TaskForTaskForm, self).__init__(*args, **kwargs)
        self.fields['executors'].queryset = self.executor_list


class CommentForTaskForm(forms.ModelForm):
    class Meta:
        model = CommentForTask
        fields = ['text', ]

        widgets = {
            'text': forms.Textarea(attrs={'class': 'form-control', 'rows': 1, 'cols': 2}),
        }


class FileForCommentForm(forms.ModelForm):
    class Meta:
        model = FileForComment
        fields = ['file', ]

        widgets = {
            'file': forms.ClearableFileInput(attrs={'multiple': True, 'class': 'form-control-file', 'required': False}),
        }
        labels = {
            "file": _("Выберите файлы"),
        }

tracker/templates/tracker/change_comment.html
{% extends 'base.html' %}

{% block title %}
    Редактирование комментария
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url "task_list_for_current_lab" lab=current_lab.slug %}">Задачи</a></li>
    <li class="breadcrumb-item"><a href="{{ task.get_absolute_url }}">{{ task }}</a></li>
    <li class="breadcrumb-item">Редактирование комменатрия</li>
{% endblock %}

{% block content %}
    <h3>Редактирование комментария у задачи <a href="{{ task.get_absolute_url }}">{{ task.name }}</a></h3>
    <form method="post" action="{{ comment.get_absolute_url_for_change }}" id="comment_form">
        {% csrf_token %}
        {{ comment_form }}
        <button type="submit" class="btn btn-outline-secondary mt-2">Сохранить</button>
    </form>
    {% if files %}
        <h3 class="mt-3">Удаление файлов</h3>
        {% for file in files %}
            <div class="row" id="file__{{ file.pk }}">
                <div class="col-4">{{ file.filename }}</div>
                <div class="col-8"><button class="btn btn-outline-danger btn-sm" data-toggle="modal" data-target="#delete_file_{{ file.pk }}">Удалить</button></div>
                <!-- Модальное окно -->
                <div class="modal fade" id="delete_file_{{ file.pk }}" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="staticBackdropLabel">Удаление файла {{ file.filename }}</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body">
                                {% csrf_token %}
                                <h5>Вы действительно хотите удалить файл {{ file.filename }}</h5>
                                <input type="hidden" name="image_pk" value="{{ image.pk }}">
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">Отмена</button>
                                <button type="button" class="btn btn-outline-danger" onclick="delete_file({{ file.pk }})">Удалить</button>
                            </div>
                        </div>
                    </div>
                </div>
                <!-------------------------------------------------------------------->
            </div>
        {% endfor %}
    {% endif %}
    <h3 class="mt-3">Добавление новых файлов</h3>
    <form method="post" action="{{ comment.get_absolute_url_for_change }}" id="files_form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ new_files_form }}
        <button type="submit" class="btn btn-outline-secondary mt-2">Добавить</button>
    </form>
{% endblock %}

{% block java_script %}
    <script>
        let comment_text_area = $('#id_text')
        var simplemde = new SimpleMDE({
            placeholder: "Введите комментрий ...",
            spellChecker: false,
            element: document.getElementById('id_text')
        });
        simplemde.codemirror.on("change", function(){
            comment_text_area.val(simplemde.value());
        });
        document.querySelector('div.editor-statusbar').remove()
    </script>
{% endblock %}

tracker/templates/tracker/task_form.html
{% extends 'base.html' %}
{% load static %}

{% block titile %}

{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url "task_list_for_current_lab" lab=current_lab.slug %}">Задачи</a></li>
    {% if task %}
        <li class="breadcrumb-item"><a href="{{ task.get_absolute_url }}">{{ task }}</a></li>
        <li class="breadcrumb-item">Обновление задачи</li>
    {% else %}
        <li class="breadcrumb-item">Добавление новой задачи</li>
    {% endif %}
{% endblock %}

{% block content %}
    {% if task %}
        <h3>Обновление задачи : <a href="{{ task.get_absolute_url }}">{{ task.name }}</a></h3>
        <form method="post" action="{% url 'update_task_url' lab=current_lab.slug pk=task.pk %}">
    {% else %}
        <h3>Добавление новой задачи</h3>
        <form method="post" action="{% url 'new_task_form_url' lab=current_lab.slug %}">
    {% endif %}

    {% csrf_token %}

    {{ form.as_p }}

    <input type="button" class="btn btn-outline-secondary" value="Назад" onClick="javascript:history.go(-1);">
    <button type="submit" class="btn btn-outline-secondary">Сохранить</button>

    </form>

{% endblock %}

{% block java_script %}
    <script>
        var simplemde = new SimpleMDE({
            placeholder: "Type here...",
            spellChecker: false,
        });
        let text_area = $('#id_text')
        document.querySelector('div.editor-statusbar').remove()

        simplemde.codemirror.on("change", function(){
            text_area.val(simplemde.value());
        });
    </script>
{% endblock %}

tracker/templates/tracker/task_list.html
{% extends 'base.html' %}

{% block title %}
    Список задач
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item">Задачи</li>
{% endblock %}

{% block content %}
    <a class="btn btn-outline-secondary mb-3" href="{% url 'new_task_form_url' lab=current_lab.slug %}" role="button">Создать задачу</a>

    {% if private_task_list %}
        <h3>Приватные задачи</h3>

        <table class="table table-hover tree-table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Название</th>
                <th scope="col">Начато</th>
                <th scope="col">Выполнить до</th>
                <th scope="col">Статус</th>
            </tr>
            </thead>

            <tbody>
            {% for task_tree in private_task_list %}
                {% for task, level in task_tree %}
                    <tr data-id="{{ task.pk }}" data-parent="{{ task.parent.pk }}" data-level="{{ level }}">
                        <td></td>
                        <td {% if task.if_get_children %}class="glyphicon-chevron-right"{% endif %} data-column="name" style="width: 55%">
                            <a href="{{ task.get_absolute_url }}">{{ task.name}}</a>{% if profile in task.new_comment_for_executors.all %} &#128276;

                        {% endif %}
                        </td>
                        <td style="width: 15%">{% if task.start_date %}{{ task.start_date }}{% endif %}</td>
                        <td style="width: 15% ;background-color: {{ task.get_color }}">{{ task.end_date }}</td>
                        <td style="width: 15%">{{ task.get_status_display }}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>
    {% endif %}
    {% if task_list %}
        <h3>Активные задачи</h3>

        <table class="table table-hover tree-table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Название</th>
                <th scope="col">Начато</th>
                <th scope="col">Выполнить до</th>
                <th scope="col">Статус</th>
            </tr>
            </thead>

            <tbody>
            {% for task_tree in task_list %}
                {% for task, level in task_tree %}
                    <tr data-id="{{ task.pk }}" data-parent="{{ task.parent.pk }}" data-level="{{ level }}">
                        <td></td>
                        <td {% if task.if_get_children %}class="glyphicon-chevron-right"{% endif %} data-column="name" style="width: 55%">
                            <a href="{{ task.get_absolute_url }}">{{ task.name}}</a>{% if profile in task.new_comment_for_executors.all %} &#128276;

                            {% endif %}
                        </td>
                        <td style="width: 15%">{% if task.start_date %}{{ task.start_date }}{% endif %}</td>
                        <td style="width: 15% ;background-color: {{ task.get_color }}">{{ task.end_date }}</td>
                        <td style="width: 15%">{{ task.get_status_display }}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <h3>Активных задач нет</h3>
    {% endif %}
    {% if done_private_task_list %}
        <h3>Приватные закрытые задачи</h3>
        <table class="table table-hover tree-table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Название</th>
                <th scope="col">Начато</th>
                <th scope="col">Закрыто</th>
                <th scope="col">Статус</th>
            </tr>
            </thead>

            <tbody>
            {% for task_tree in done_private_task_list %}
                {% for task, level in task_tree %}
                    <tr data-id="{{ task.pk }}" data-parent="{{ task.parent.pk }}" data-level="{{ level }}">
                        <td></td>
                        <td {% if task.if_get_children %}class="glyphicon-chevron-right"{% endif %} data-column="name" style="width: 55%">
                            <a href="{{ task.get_absolute_url }}">{{ task.name}}</a>
                        </td>
                        <td style="width: 15%">{% if task.start_date %}{{ task.start_date }}{% endif %}</td>
                        <td style="width: 15%}">{{ task.close_date }}</td>
                        <td style="width: 15%">{{ task.get_status_display }}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

    {% if done_task_list %}
        <h3>Закрытые задачи</h3>
        <table class="table table-hover tree-table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Название</th>
                <th scope="col">Начато</th>
                <th scope="col">Закрыто</th>
                <th scope="col">Статус</th>
            </tr>
            </thead>

            <tbody>
            {% for task_tree in done_task_list %}
                {% for task, level in task_tree %}
                    <tr data-id="{{ task.pk }}" data-parent="{{ task.parent.pk }}" data-level="{{ level }}">
                        <td></td>
                        <td {% if task.if_get_children %}class="glyphicon-chevron-right"{% endif %} data-column="name" style="width: 55%">
                            <a href="{{ task.get_absolute_url }}">{{ task.name}}</a>
                        </td>
                        <td style="width: 15%">{% if task.start_date %}{{ task.start_date }}{% endif %}</td>
                        <td style="width: 15%}">{{ task.close_date }}</td>
                        <td style="width: 15%">{{ task.get_status_display }}</td>
                    </tr>
                {% endfor %}
            {% endfor %}
            </tbody>
        </table>
    {% endif %}

{% endblock %}